install: true
script: true
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = develop
addons:
  apt:
    packages:
      - sshpass
