version: '3.2'
services:
  web:
    image: nginx
    volumes:
      - type: bind
        source: ./sources
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: ./logs
        target: /var/log/nginx
    ports:
      - "8080:80"
